spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog?useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.80.101
      port: 6379
      password: 123456
      database: 1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  mail:
    host: smtp.qq.com
    port: 587
    username: 2252559105@qq.com
    password: fpazmmwwbqtadjci
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  jackson:
    default-property-inclusion: non_null #JOSN处理时忽略非空字段

# 设置日志输出
logging:
  level:
    com:
      jackson:
        mapper: debug
        service: info
        controller: info
server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.jackson.pojo

aliyun:
  oss:
    endpoint: yourEndpoint
    accessKeyId: yourAccessKeyId
    accessKeySecret: yourAccessKeySercret
    bucketName: yourBuckeetName
